"""Pre-render script: generate docs/tutorials/_tutorials_table.qmd.

Walks the tutorials sidebar in _quarto.yml, extracts title and description
from each notebook's markdown header cell, and writes a Quarto include file
containing the section headers and tables.

tutorials/index.qmd includes this file via a Quarto include shortcode
so the table stays in sync with the sidebar without manual maintenance.
"""

import json
import re
from pathlib import Path

import yaml

DOCS_DIR = Path(__file__).parent.parent
REPO_ROOT = DOCS_DIR.parent
QUARTO_CONFIG = DOCS_DIR / "_quarto.yml"
OUT = DOCS_DIR / "tutorials" / "_tutorials_table.qmd"


def _normalize_entry(entry):
    """Normalize Quarto sidebar entries to dicts the renderer can traverse."""
    if isinstance(entry, str):
        return {"href": entry}
    if "section" in entry:
        return {
            "section": entry["section"],
            "contents": [_normalize_entry(item) for item in entry.get("contents", [])],
        }
    return entry


def _load_sidebar() -> list[dict]:
    """Load the tutorials sidebar contents from _quarto.yml."""
    config = yaml.safe_load(QUARTO_CONFIG.read_text(encoding="utf-8"))
    for sidebar in config.get("website", {}).get("sidebar", []):
        if sidebar.get("id") == "tutorials":
            contents = [_normalize_entry(entry) for entry in sidebar.get("contents", [])]
            return [entry for entry in contents if entry.get("href") != "tutorials/index.qmd"]
    raise ValueError("Could not find tutorials sidebar in _quarto.yml")


def _parse_header(source: list[str]) -> dict:
    """Extract title and description from a markdown header cell."""
    text = "".join(source)
    title_m = re.search(r"^#\s+(.+)", text, re.MULTILINE)
    desc_m = re.search(r"_Description:_\s*(.+)", text)
    return {
        "title": title_m.group(1).strip() if title_m else None,
        "description": desc_m.group(1).strip() if desc_m else None,
    }


def _notebook_meta(href: str) -> dict:
    """Return title and description for a notebook, given its docs-relative href."""
    nb_path = REPO_ROOT / "notebooks" / Path(href).relative_to("notebooks")
    if not nb_path.exists():
        return {"title": href, "description": ""}
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    if not nb["cells"]:
        return {"title": href, "description": ""}
    return _parse_header(nb["cells"][0]["source"])


def _table_row(entry: dict) -> str:
    meta = _notebook_meta(entry["href"])
    text = entry.get("text") or meta["title"] or Path(entry["href"]).stem
    desc = meta["description"] or ""
    link = f"[{text}](../{entry['href']})"
    return f"| {link} | {desc} |"


def _render_section(section: dict, level: int) -> list[str]:
    """Recursively render a section as markdown lines."""
    hashes = "#" * level
    lines = [f"{hashes} {section['section']}", ""]
    pending_notebooks: list[dict] = []

    def _flush_notebooks():
        if pending_notebooks:
            lines.extend(["| Notebook | What it shows |", "|---|---|"])
            lines.extend(_table_row(nb) for nb in pending_notebooks)
            lines.append("")
            pending_notebooks.clear()

    for entry in section["contents"]:
        if "href" in entry:
            pending_notebooks.append(entry)
        else:
            _flush_notebooks()
            lines += _render_section(entry, level + 1)
    _flush_notebooks()

    return lines


def generate():
    lines = [
        "<!-- AUTO-GENERATED by scripts/generate_tutorials_index.py — do not edit by hand -->",
        "",
    ]
    for entry in _load_sidebar():
        lines += _render_section(entry, level=2)

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generate_tutorials_index: wrote {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    generate()
